### ISSUE TITLE
[로그인] 비밀번호 찾기 이슈

### ISSUE THREAD

**Issue by CodingPythonMan** [Jogging-Kim-Chaebak/PuppyPlaytime#141]
아직 비밀번호 찾기가 완전히 구현 안된 것으로 확인됩니다.

구현되는대로 알려주시면 감사하겠습니다.

담당자 : @min-eui

**Comment by min-eui** [comment]
이메일 인증 후 비밀번호 변경이 가능하게 구현했습니다.

**Comment by CodingPythonMan** [comment]
![image](https://user-images.githubusercontent.com/27558778/148675170-220b3bcb-ccef-42b0-8c9d-93f90833fe8c.png)

아이디는 같지 않아도 이메일만 입력하면 인증이 되는 이슈가 있습니다. 해당 사항은 제가 식별했으니 제가 수정해보겠습니다.

**Comment by CodingPythonMan** [comment]
![image](https://user-images.githubusercontent.com/27558778/148676031-23f37d4b-5e69-4629-8817-20c125058b7a.png)

해당 문제 ajax 에서 id와 pw 둘다 보내기로 하였습니다.

![image](https://user-images.githubusercontent.com/27558778/148676072-11c3b269-762a-4805-a782-5d4d4ef831f9.png)

둘다 보낸 값으로 id로는 m_email을 찾아오고 그 m_email과 email을 비교하는 방식으로 하였습니다.

**Comment by CodingPythonMan** [comment]
현재 잘되는 것 같아 해당 이슈 닫도록 하겠습니다! 담당자님 확인하느라 수고하셨습니다.
